backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  - name: "artistes" # Used in routes, e.g., /admin/collections/blog
    label: "Artistes" # Used in the UI
    folder: "/artistes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Nom", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "artist"}
      - {label: "Styles", name: "styles", widget: "list", allow_add: true}
      - {label: "Photo", name: "pic", widget: "image"}
      - {label: "Facebook", name: "facebook", widget: "string",required: false}
      - {label: "Twitter", name: "twitter", widget: "string",required: false}
      - {label: "Instagram", name: "instagram", widget: "string",required: false}
      - {label: "Youtube", name: "youtube", widget: "string",required: false}
      - {label: "Soundcloud", name: "soundcloud", widget: "string",required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "article"}
      - {label: "Catégories", name: "categories", widget: "list"}
      - {label: "Photo", name: "pic", widget: "image"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "evenements" # Used in routes, e.g., /admin/collections/blog
    label: "Évenements" # Used in the UI
    folder: "/evenements" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "event"}
      - {label: "Lieu", name: "place", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Configuration"
    name: "home"
    files:
      - label: "Accueil"
        name: "home"
        file: "site/config.md"
        fields:
          - {label: "Présentation", name: "intro", widget: "markdown"}
          - {label: "Twitter", name: "twitter", widget: "string"}
          - {label: "Instagram", name: "instagram", widget: "string"}